export const GET_POSTS = 'GET_POSTS';

export const UPDATE_POSTS_LIST = 'UPDATE_POSTS_LIST';
export const CHANGE_POSTS = 'CHANGE_POSTS';
export const CREATE_POST = 'CREATE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';

export const SHOW_ARTICLE_MANAGEMENT_WINDOW = 'SHOW_ARTICLE_MANAGEMENT_WINDOW';
export const HIDE_ARTICLE_MANAGEMENT_WINDOW = 'HIDE_ARTICLE_MANAGEMENT_WINDOW';
