export const UPDATE_NAV_TEXT = "UPDATE_NAV_TEXT";
export const UPDATE_TEST = "UPDATE_TEST";

export const UPDATE_POSTS_LIST = "UPDATE_POSTS_LIST";
export const CHANGE_POSTS = "CHANGE_POSTS";

export const SHOW_ARTICLE_MANAGEMENT_WINDOW = "SHOW_ARTICLE_MANAGEMENT_WINDOW";
export const HIDE_ARTICLE_MANAGEMENT_WINDOW = "HIDE_ARTICLE_MANAGEMENT_WINDOW";
